# Generated by Django 4.1.2 on 2022-12-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_rename_user_name_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_age',
        ),
    ]
