# Generated by Django 4.1.2 on 2022-12-10 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_remove_user_user_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user_name',
        ),
    ]
